### PR TITLE
Added Brazil ADM1 capabilities

### LINKED ISSUE #66: Necessary steps to implement a new country without p-codes (like Brazil)
TL;DR: **this question is both about how to add the geometry on the hxldash and how to choose p-codes for countries that already do not have p-codes on OCHA...** BUT may already have some well used codes outside humanitarian area. These P-codes are also more resilient than use IDs based on descending order of cities names or names of cities (that may be either in English, or in the local language and have characters like ç )

---

I just discovered about the hxldash.com yesterday after looking for visualizations to datasets following HXL Standard. On our case, we're looking to eventually implement visualizations on some [CPLP countries](https://en.wikipedia.org/wiki/Community_of_Portuguese_Language_Countries). The hxldash seems to already support 2 CPLP countries (AGO/Angola) and (MOZ/Mozambique). The other two big countries from CPLP that hxldash already does not have one optimized way to implement is Portugal and (near continental size) Brazil.

Looking at both the HXL Standard and the hxldash source code it seems that be best way to document a location would be use p-codes (I'm actually new to HXL Standard, so I'm not sure if already have p-codes is and enforcement to use hxldash or something that make it easier to use but could be replaced by other verbose means; if there is actually other ways, we're also interested to know!).

As for this issue, I will try first consider just Brazil, because for very short term I both already know where to get the geometries and also am aware of well used internal codes to point to places. For Portugal and other CPLP countries I would be less confident.

### Point one - the geometry optimized for web

Question 1.1: **the format used is topojoson?**

Question 1.2: **which minimum metadata should the geometry have to use on hxldash?**

> Using Brasil as reference, 
> 
> - for state level, I already have this file https://github.com/fititnt/gis-dataset-brasil/blob/master/uf/topojson/uf.json
>   - (248KB still have room for size reduction)
> - Brazil have "mesorregiao" (I'm not sure if should be added, but just to mention that it have)
> - Brazil have "microrregiao" (I'm not sure if should be added, but just to mention that it have)
> - For "city", is this folder https://github.com/fititnt/gis-dataset-brasil/tree/master/municipio/topojson
>   - Brazil have lot's of cities, so the bigger file is 3.45 MB, while the smallest one is 816 KB, but is not really usable
>
> In special for the city geometry, I would need to regenerate from the updated shapefiles, since the repository gis-dataset-brasil is not up to date

### Point two - P-Codes to use on hxldash

I suppose that the first step to look for P-Codes would be try to find already established codes. 

This is an example of very explicitly codes already defined:

- At the https://vocabulary.unocha.org/, they point to https://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External
  - The countries on this link, also have datasets marked as "CODs" here https://data.humdata.org/search and these datasets explicitly have an unique ID for `#admin0-3` codes
    - MOZ: https://data.humdata.org/dataset/mozambique-administrative-levels-0-3
    - AGO: https://data.humdata.org/dataset/angola-administrative-levels-0-3

Then, we have Brazil. At the https://data.humdata.org/, it actually have shapefiles (here https://data.humdata.org/dataset/brazil-administrative-level-0-boundaries) from admin0 to admin3. But these files, while have name of the regions in portuguese, they don't explicitly set an P-Code.

> At least using Brazil as reference, both for what data.humandata.org already have (the BRA_admin1, BRA_admin2, BRA_admin3) on Brazil the IBGE (https://www.ibge.gov.br/, https://en.wikipedia.org/wiki/Brazilian_Institute_of_Geography_and_Statistics) already have an unique identifier for each of these BRA_admin1, BRA_admin2, BRA_admin3.
>
> For a quick list of IBGE codes, there is this link https://www.ibge.gov.br/explica/codigos-dos-municipios.php.
>
> But, in short, as example, the code for the a city, from the state level to other divisions, would be
> 
> - **`31` is the code for the state of "Minas Gerais" (and alternative is "MG")**
> - `3107` is the code for the mesorregiao "metropolitana de Belo Horizonte"
> - `31030` is the code for the microrregiao of "Belo Horizonte"
> - **`3106200` is the code for the (capital) city "Belo Horizonte"**
>
> The IBGE codes are used on a huge number of internal systems on Brazil, so any change are likely to be also a change on region borders. Old codes tend to be not reused. Using the IBGE codes as quickstart to P-codes for Brazil also have the advantage of every shapefile that is released each year also have these same codes.
>
> If using the https://data.humdata.org/dataset/brazil-administrative-level-0-boundaries way, it seems that for `#adm1 if uses `HASC_1: BR.MG` for Minas Gerais State and Belo Horizonte city the `HASC_2` is empty, and `ID_2: 1606` is just an sequential ID based on desc order (very likely to change by just adding/removing a city)

----

### My initial proposal

So, just to finish my initial thought here, to generate the geometries for hxldash, it seems a good idea to reuse the IBGE codes with a prefix for the country (I'm not sure if most P-codes use the 2 leter iso or the 3 letter iso) But assuming most P-codes uses 2 letter iso, this would means:

- `#adm1`: The Minas Gerais State would have a P-Code of BR31
- `#adm2`: The Belo Horizonte city would have a P-Code of BR3106200
- `#adm3`: (don't implement at this moment)

If other P-Codes already use iso3, or there is a thrend to use iso 3, then on this example would be `#adm1: BRA31` and `#adm2: BRA3106200`.

If you are Ok with this, I could try help generate the geometry files and open a Pull request. But definely how the "admin2Pcode" value was decided was something I would ask opinion before and give strong reasoning to use the IBGE codes after the country prefix.

### PR DESCRIPTION
**Pull request by Rydela**
Created pcodes for Brazil and added visual possibility of ADM1 (State/UF) level.

### CODE REVIEW

**Comment by fititnt** [comment]
On a quick look, the admin1Pcode needs revision. Rio de Janeiro seems right, but several others ( like São Paulo) seems to have a different number. On this example:

- São Paulo **admin1Pcode**: BR51
- São Paulo **IBGE code**: 35

While (just for State/UF) would be possible to just edit manually, when come to commit the cities this would hard if we somewhat don't extract the codes from the database that comes with the shapefiles. But for the first commit I could just edit the direct file, and later we see how to create the cities.


### Current commit

I'm using this URL to preview https://github.com/SimonbJohnson/quickX3/blob/development/hxldash/static/geoms/topojson/BRA/1/geom.json (exact version: https://github.com/SimonbJohnson/quickX3/blob/2cee17881d49133367eb66712ecea6aedddb5bc5/hxldash/static/geoms/topojson/BRA/1/geom.json)

Captura de tela de 2020-05-01 23-33-34

---

### IBGE references

In addition to the shapefiles, here some places that have the numbers:

#### https://www.ibge.gov.br/explica/codigos-dos-municipios.php

Captura de tela de 2020-05-01 23-38-09

#### ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2018/Leia_me_Malha_Digital_2018.pdf

Captura de tela de 2020-05-01 23-38-45

--- 

#### What I did not tested.

I did not checked if the file size could be optimized for be less than 188 KB with acceptable loss of precision to save page load.

**Comment by Rydela** [comment]
> On a quick look, the admin1Pcode needs revision. Rio de Janeiro seems right, but several others ( like São Paulo) seems to have a different number. 

Thanks for pointing that out, I had to review what happened. I think the UF names were sorted alphabetically somewhere and the códigos got out of order when that happened. I'll fix it today.

**Comment by fititnt** [comment]
@Rydela I can confirm that now the the 27 UFs are exactly the IBGE code prefixed with BR.

Thanks!

**Comment by SimonbJohnson** [comment]
Great work @Rydela

**Pull request merged**
