### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Rydela**
This is collection of commits made in the development branch. It includes moving filter to the last step of the dashboard creation process and adding Brazil admin 2 levels.

### CODE REVIEW

**Comment by SimonbJohnson** [comment]
Looks great Ryan, merging.  Do you have a test data set for Brazil adm2?

**Comment by fititnt** [comment]
@SimonbJohnson this change is already on the https://hxldash.com/ ?

**Comment by SimonbJohnson** [comment]
No, not yet. I will update the server next week and ping when you it is done.

**Comment by fititnt** [comment]
One dateset that can already have all IBGE codes (both at city and state) can be found here https://data.brasil.io/dataset/covid19/_meta/list.html (more specicaly this file https://data.brasil.io/dataset/covid19/caso.csv.gz). A dashboard with cities can be found at https://brasil.io/covid19/.

The field that contain the code is `city_ibge_code`, so it is likely to be just prefix `BR` + `value of caso.csv city_ibge_code`.

One practical problem of this dataset is that is somewhat big. The caso.csv uncompressed is 17.2MB since it does not only get the lastest case, it actually get past recent numbers of Covid cases, but the rows that are last have the field `is_last = TRUE`.

Also most of the columns already are in English, they just are not tagged with HXL tags.

**Comment by SimonbJohnson** [comment]
That's a great dataset. We can use the HXL Proxy to filter to just the latest values. I will see if we can set the cache time to 24 hours as well.

Edit: Ah the csv is compressed, so it isn't possible to pull from there directly

**Pull request merged**
